language: python
python:
  - "3.9"
install:
  - pip install -r requirements_ci.txt
script:
  - python -m compileall .
  - python -m pycodestyle .
  - python -m flake8 .
  - python -m build --outdir=dist .
  - python -m pip install --verbose dist/*.whl
  - python -m pip list
  - python -m pip freeze
  - ls -laR .
  - python -m pip uninstall --yes --verbose pyzendesk
